#!/usr/bin/env python3
"""Record the C compiler's view of every libghostty-vt type this crate marshals.

The safe wrappers in `src/` hand pointers to C and rely on Rust and C agreeing on
each type's size and alignment. Getting that wrong is a memory-safety bug rather
than a cosmetic one: a mismatch on `GhosttyStyle`, for example, means the library
writes 68 bytes into a 4-byte slot. That exact bug was found by a test, so the
check is now mechanical.

This script compiles a throwaway C program against the real headers, runs it, and
writes `tests/abi_layout.txt`:

    # generated by tools/dump_abi_layout.py
    # observed: <ISO-8601 date>
    # compiler: <cc --version first line>
    # headers:  <path to include/ghostty/vt.h>
    GhosttyStyle size=72 align=8
    ...

`tests/abi_layout.rs` reads that file and compares it against Rust's
`size_of`/`align_of` for the mirrored types, so the comparison is a normal test
that needs no C compiler at test time. Regenerate the file whenever the headers
change.

Usage:
    python3 tools/dump_abi_layout.py            # rewrite tests/abi_layout.txt
    python3 tools/dump_abi_layout.py --check    # exit 1 if the file is stale
"""

from __future__ import annotations

import argparse
import datetime
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
CRATE_ROOT = os.path.dirname(HERE)
REPO_ROOT = os.path.dirname(CRATE_ROOT)
INCLUDE_DIR = os.path.join(REPO_ROOT, "include")
FFI_PATH = os.path.join(CRATE_ROOT, "src", "ffi.rs")
OUT_PATH = os.path.join(CRATE_ROOT, "tests", "abi_layout.txt")

# Types the safe wrappers marshal across the FFI boundary. Each one is either
# written by the library into a caller-provided slot, or read by the library from
# a caller-provided pointer, so a layout disagreement is unsound.
MIRRORED_TYPES = [
    # allocator.h
    "GhosttyAllocator",
    "GhosttyAllocatorVtable",
    # color.h
    "GhosttyColorRgb",
    "GhosttyColorPaletteMask",
    # grid_ref.h
    "GhosttyGridRef",
    # scalar aliases the wrappers pass around
    "GhosttyCell",
    "GhosttyColorPaletteIndex",
    "GhosttyMode",
    "GhosttyMods",
    "GhosttyRow",
    "GhosttyStyleId",
    # io.h
    "GhosttyReader",
    "GhosttyWriter",
    # mouse/encoder.h
    "GhosttyMouseEncoderSize",
    # mouse/event.h
    "GhosttyMousePosition",
    # point.h
    "GhosttyPoint",
    "GhosttyPointCoordinate",
    "GhosttyPointValue",
    # render.h
    "GhosttyRenderStateColors",
    "GhosttyRenderStateCursor",
    "GhosttyRenderStateRowSelection",
    # selection.h
    "GhosttySelection",
    "GhosttySelectionBuffer",
    # style.h
    "GhosttyStyle",
    "GhosttyStyleColor",
    "GhosttyStyleColorValue",
    # terminal.h
    "GhosttyTerminalModeConfig",
    "GhosttyTerminalProgressReport",
    "GhosttyTerminalScrollViewport",
    "GhosttyTerminalScrollViewportValue",
    "GhosttyTerminalScrollbar",
    # size_report.h
    "GhosttySizeReportSize",
    "GhosttySizeReportStyle",
    # types.h
    "GhosttyBuffer",
    "GhosttyCodepoints",
    "GhosttyString",
    "GhosttySurfacePosition",
]


def declared_types() -> set[str]:
    """Every `Ghostty*` type name declared in `src/ffi.rs`.

    Covers emitted structs, unions, and the `c_int` type aliases that stand in
    for C enums, so an enum's size/alignment is checked too.
    """
    src = open(FFI_PATH, encoding="utf-8").read()
    names = set(re.findall(r"pub (?:struct|union) (Ghostty[A-Za-z0-9_]*)\b", src))
    names |= set(re.findall(r"pub type (Ghostty[A-Za-z0-9_]*)\s*=", src))
    return names


def find_compiler() -> list[str] | None:
    """Return a working `cc` command line, preferring the Xcode SDK on macOS."""
    candidates: list[list[str]] = []
    if sys.platform == "darwin":
        try:
            sdk = subprocess.run(
                ["xcrun", "--sdk", "macosx", "--show-sdk-path"],
                capture_output=True,
                text=True,
                check=True,
            ).stdout.strip()
            cc = subprocess.run(
                ["xcrun", "--sdk", "macosx", "-f", "clang"],
                capture_output=True,
                text=True,
                check=True,
            ).stdout.strip()
            if sdk and cc:
                candidates.append([cc, "-isysroot", sdk])
        except (subprocess.CalledProcessError, FileNotFoundError):
            pass
    for cc in ("cc", "clang", "gcc"):
        if shutil.which(cc):
            candidates.append([cc])

    for candidate in candidates:
        try:
            probe = subprocess.run(
                candidate + ["-x", "c", "-", "-o", os.devnull, "-"],
                input="int main(void){return 0;}\n",
                capture_output=True,
                text=True,
            )
        except OSError:
            continue
        if probe.returncode == 0:
            return candidate
    return None


def build_program(types: list[str]) -> str:
    lines = [
        "#include <stdalign.h>",
        "#include <stdio.h>",
        "#include <ghostty/vt.h>",
        "",
        "int main(void) {",
    ]
    for name in types:
        lines.append(
            f'  printf("{name} size=%zu align=%zu\\n", sizeof({name}), alignof({name}));'
        )
    lines += ["  return 0;", "}"]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if stale")
    args = ap.parse_args()

    declared = declared_types()
    missing_from_binding = [t for t in MIRRORED_TYPES if t not in declared]
    if missing_from_binding:
        print(
            "these types are in the checked list but not in src/ffi.rs: "
            + ", ".join(missing_from_binding),
            file=sys.stderr,
        )
        return 2

    cc_cmd = find_compiler()
    if cc_cmd is None:
        print("no working C compiler found; cannot dump the ABI layout", file=sys.stderr)
        return 2

    program = build_program(MIRRORED_TYPES)
    with tempfile.TemporaryDirectory() as tmp:
        src = os.path.join(tmp, "abi_layout.c")
        exe = os.path.join(tmp, "abi_layout")
        with open(src, "w", encoding="utf-8") as fh:
            fh.write(program)
        compile_cmd = cc_cmd + [
            "-std=c11",
            f"-I{INCLUDE_DIR}",
            src,
            "-o",
            exe,
        ]
        compiled = subprocess.run(compile_cmd, capture_output=True, text=True)
        if compiled.returncode != 0:
            print("failed to compile the ABI probe:\n" + compiled.stderr, file=sys.stderr)
            return 2
        run = subprocess.run([exe], capture_output=True, text=True, check=True)

    version = subprocess.run(cc_cmd + ["--version"], capture_output=True, text=True)
    version_line = (version.stdout or version.stderr).splitlines()[0].strip() if version.stdout or version.stderr else "unknown"

    observed = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    body = [line.strip() for line in run.stdout.splitlines() if line.strip()]
    text = "\n".join(
        [
            "# ABI layout of libghostty-vt types marshalled by khostty-vt.",
            "# Generated by tools/dump_abi_layout.py -- do not edit by hand.",
            f"# observed: {observed}",
            f"# compiler: {version_line}",
            f"# headers:  include/ghostty/vt.h",
            *body,
            "",
        ]
    )
    # Keep the compiler path out of the file: it differs per machine and would
    # make the committed snapshot churn.
    text = re.sub(r"# compiler: .*", f"# compiler: {version_line}", text)

    if args.check:
        existing = open(OUT_PATH, encoding="utf-8").read() if os.path.exists(OUT_PATH) else ""
        # Compare only the measured lines; the date and compiler strings are
        # observation metadata and legitimately change.
        def measured(blob: str) -> list[str]:
            return [
                line
                for line in blob.splitlines()
                if line and not line.startswith("#")
            ]

        if measured(existing) != measured(text):
            print(
                "tests/abi_layout.txt is stale; run tools/dump_abi_layout.py",
                file=sys.stderr,
            )
            return 1
        print("tests/abi_layout.txt is up to date")
        return 0

    with open(OUT_PATH, "w", encoding="utf-8") as fh:
        fh.write(text)

    print(f"wrote {OUT_PATH}: {len(body)} types, observed {observed}")
    print(f"compiler: {' '.join(cc_cmd)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
