// Code generated by tools/genkeys from libghostty-vt's own type
// manifest. DO NOT EDIT.
//
// Regenerate with:
//
//	go run ./tools/genkeys > keys_gen.go

package khostty

import "fmt"

// Physical key codes, mirroring GhosttyKey.
//
// The values come from the linked library, so they always match the build
// these bindings are used with.
const (
	KeyUnidentified         Key = 0
	KeyBackquote            Key = 1
	KeyBackslash            Key = 2
	KeyBracketLeft          Key = 3
	KeyBracketRight         Key = 4
	KeyComma                Key = 5
	KeyDigit0               Key = 6
	KeyDigit1               Key = 7
	KeyDigit2               Key = 8
	KeyDigit3               Key = 9
	KeyDigit4               Key = 10
	KeyDigit5               Key = 11
	KeyDigit6               Key = 12
	KeyDigit7               Key = 13
	KeyDigit8               Key = 14
	KeyDigit9               Key = 15
	KeyEqual                Key = 16
	KeyIntlBackslash        Key = 17
	KeyIntlRo               Key = 18
	KeyIntlYen              Key = 19
	KeyA                    Key = 20
	KeyB                    Key = 21
	KeyC                    Key = 22
	KeyD                    Key = 23
	KeyE                    Key = 24
	KeyF                    Key = 25
	KeyG                    Key = 26
	KeyH                    Key = 27
	KeyI                    Key = 28
	KeyJ                    Key = 29
	KeyK                    Key = 30
	KeyL                    Key = 31
	KeyM                    Key = 32
	KeyN                    Key = 33
	KeyO                    Key = 34
	KeyP                    Key = 35
	KeyQ                    Key = 36
	KeyR                    Key = 37
	KeyS                    Key = 38
	KeyT                    Key = 39
	KeyU                    Key = 40
	KeyV                    Key = 41
	KeyW                    Key = 42
	KeyX                    Key = 43
	KeyY                    Key = 44
	KeyZ                    Key = 45
	KeyMinus                Key = 46
	KeyPeriod               Key = 47
	KeyQuote                Key = 48
	KeySemicolon            Key = 49
	KeySlash                Key = 50
	KeyAltLeft              Key = 51
	KeyAltRight             Key = 52
	KeyBackspace            Key = 53
	KeyCapsLock             Key = 54
	KeyContextMenu          Key = 55
	KeyControlLeft          Key = 56
	KeyControlRight         Key = 57
	KeyEnter                Key = 58
	KeyMetaLeft             Key = 59
	KeyMetaRight            Key = 60
	KeyShiftLeft            Key = 61
	KeyShiftRight           Key = 62
	KeySpace                Key = 63
	KeyTab                  Key = 64
	KeyConvert              Key = 65
	KeyKanaMode             Key = 66
	KeyNonConvert           Key = 67
	KeyDelete               Key = 68
	KeyEnd                  Key = 69
	KeyHelp                 Key = 70
	KeyHome                 Key = 71
	KeyInsert               Key = 72
	KeyPageDown             Key = 73
	KeyPageUp               Key = 74
	KeyArrowDown            Key = 75
	KeyArrowLeft            Key = 76
	KeyArrowRight           Key = 77
	KeyArrowUp              Key = 78
	KeyNumLock              Key = 79
	KeyNumpad0              Key = 80
	KeyNumpad1              Key = 81
	KeyNumpad2              Key = 82
	KeyNumpad3              Key = 83
	KeyNumpad4              Key = 84
	KeyNumpad5              Key = 85
	KeyNumpad6              Key = 86
	KeyNumpad7              Key = 87
	KeyNumpad8              Key = 88
	KeyNumpad9              Key = 89
	KeyNumpadAdd            Key = 90
	KeyNumpadBackspace      Key = 91
	KeyNumpadClear          Key = 92
	KeyNumpadClearEntry     Key = 93
	KeyNumpadComma          Key = 94
	KeyNumpadDecimal        Key = 95
	KeyNumpadDivide         Key = 96
	KeyNumpadEnter          Key = 97
	KeyNumpadEqual          Key = 98
	KeyNumpadMemoryAdd      Key = 99
	KeyNumpadMemoryClear    Key = 100
	KeyNumpadMemoryRecall   Key = 101
	KeyNumpadMemoryStore    Key = 102
	KeyNumpadMemorySubtract Key = 103
	KeyNumpadMultiply       Key = 104
	KeyNumpadParenLeft      Key = 105
	KeyNumpadParenRight     Key = 106
	KeyNumpadSubtract       Key = 107
	KeyNumpadSeparator      Key = 108
	KeyNumpadUp             Key = 109
	KeyNumpadDown           Key = 110
	KeyNumpadRight          Key = 111
	KeyNumpadLeft           Key = 112
	KeyNumpadBegin          Key = 113
	KeyNumpadHome           Key = 114
	KeyNumpadEnd            Key = 115
	KeyNumpadInsert         Key = 116
	KeyNumpadDelete         Key = 117
	KeyNumpadPageUp         Key = 118
	KeyNumpadPageDown       Key = 119
	KeyEscape               Key = 120
	KeyF1                   Key = 121
	KeyF2                   Key = 122
	KeyF3                   Key = 123
	KeyF4                   Key = 124
	KeyF5                   Key = 125
	KeyF6                   Key = 126
	KeyF7                   Key = 127
	KeyF8                   Key = 128
	KeyF9                   Key = 129
	KeyF10                  Key = 130
	KeyF11                  Key = 131
	KeyF12                  Key = 132
	KeyF13                  Key = 133
	KeyF14                  Key = 134
	KeyF15                  Key = 135
	KeyF16                  Key = 136
	KeyF17                  Key = 137
	KeyF18                  Key = 138
	KeyF19                  Key = 139
	KeyF20                  Key = 140
	KeyF21                  Key = 141
	KeyF22                  Key = 142
	KeyF23                  Key = 143
	KeyF24                  Key = 144
	KeyF25                  Key = 145
	KeyFn                   Key = 146
	KeyFnLock               Key = 147
	KeyPrintScreen          Key = 148
	KeyScrollLock           Key = 149
	KeyPause                Key = 150
	KeyBrowserBack          Key = 151
	KeyBrowserFavorites     Key = 152
	KeyBrowserForward       Key = 153
	KeyBrowserHome          Key = 154
	KeyBrowserRefresh       Key = 155
	KeyBrowserSearch        Key = 156
	KeyBrowserStop          Key = 157
	KeyEject                Key = 158
	KeyLaunchApp1           Key = 159
	KeyLaunchApp2           Key = 160
	KeyLaunchMail           Key = 161
	KeyMediaPlayPause       Key = 162
	KeyMediaSelect          Key = 163
	KeyMediaStop            Key = 164
	KeyMediaTrackNext       Key = 165
	KeyMediaTrackPrevious   Key = 166
	KeyPower                Key = 167
	KeySleep                Key = 168
	KeyAudioVolumeDown      Key = 169
	KeyAudioVolumeMute      Key = 170
	KeyAudioVolumeUp        Key = 171
	KeyWakeUp               Key = 172
	KeyCopy                 Key = 173
	KeyCut                  Key = 174
	KeyPaste                Key = 175
)

// keyNames maps every generated key constant back to its C name, for
// error messages and test failures.
var keyNames = map[Key]string{
	KeyUnidentified:         "UNIDENTIFIED",
	KeyBackquote:            "BACKQUOTE",
	KeyBackslash:            "BACKSLASH",
	KeyBracketLeft:          "BRACKET_LEFT",
	KeyBracketRight:         "BRACKET_RIGHT",
	KeyComma:                "COMMA",
	KeyDigit0:               "DIGIT_0",
	KeyDigit1:               "DIGIT_1",
	KeyDigit2:               "DIGIT_2",
	KeyDigit3:               "DIGIT_3",
	KeyDigit4:               "DIGIT_4",
	KeyDigit5:               "DIGIT_5",
	KeyDigit6:               "DIGIT_6",
	KeyDigit7:               "DIGIT_7",
	KeyDigit8:               "DIGIT_8",
	KeyDigit9:               "DIGIT_9",
	KeyEqual:                "EQUAL",
	KeyIntlBackslash:        "INTL_BACKSLASH",
	KeyIntlRo:               "INTL_RO",
	KeyIntlYen:              "INTL_YEN",
	KeyA:                    "A",
	KeyB:                    "B",
	KeyC:                    "C",
	KeyD:                    "D",
	KeyE:                    "E",
	KeyF:                    "F",
	KeyG:                    "G",
	KeyH:                    "H",
	KeyI:                    "I",
	KeyJ:                    "J",
	KeyK:                    "K",
	KeyL:                    "L",
	KeyM:                    "M",
	KeyN:                    "N",
	KeyO:                    "O",
	KeyP:                    "P",
	KeyQ:                    "Q",
	KeyR:                    "R",
	KeyS:                    "S",
	KeyT:                    "T",
	KeyU:                    "U",
	KeyV:                    "V",
	KeyW:                    "W",
	KeyX:                    "X",
	KeyY:                    "Y",
	KeyZ:                    "Z",
	KeyMinus:                "MINUS",
	KeyPeriod:               "PERIOD",
	KeyQuote:                "QUOTE",
	KeySemicolon:            "SEMICOLON",
	KeySlash:                "SLASH",
	KeyAltLeft:              "ALT_LEFT",
	KeyAltRight:             "ALT_RIGHT",
	KeyBackspace:            "BACKSPACE",
	KeyCapsLock:             "CAPS_LOCK",
	KeyContextMenu:          "CONTEXT_MENU",
	KeyControlLeft:          "CONTROL_LEFT",
	KeyControlRight:         "CONTROL_RIGHT",
	KeyEnter:                "ENTER",
	KeyMetaLeft:             "META_LEFT",
	KeyMetaRight:            "META_RIGHT",
	KeyShiftLeft:            "SHIFT_LEFT",
	KeyShiftRight:           "SHIFT_RIGHT",
	KeySpace:                "SPACE",
	KeyTab:                  "TAB",
	KeyConvert:              "CONVERT",
	KeyKanaMode:             "KANA_MODE",
	KeyNonConvert:           "NON_CONVERT",
	KeyDelete:               "DELETE",
	KeyEnd:                  "END",
	KeyHelp:                 "HELP",
	KeyHome:                 "HOME",
	KeyInsert:               "INSERT",
	KeyPageDown:             "PAGE_DOWN",
	KeyPageUp:               "PAGE_UP",
	KeyArrowDown:            "ARROW_DOWN",
	KeyArrowLeft:            "ARROW_LEFT",
	KeyArrowRight:           "ARROW_RIGHT",
	KeyArrowUp:              "ARROW_UP",
	KeyNumLock:              "NUM_LOCK",
	KeyNumpad0:              "NUMPAD_0",
	KeyNumpad1:              "NUMPAD_1",
	KeyNumpad2:              "NUMPAD_2",
	KeyNumpad3:              "NUMPAD_3",
	KeyNumpad4:              "NUMPAD_4",
	KeyNumpad5:              "NUMPAD_5",
	KeyNumpad6:              "NUMPAD_6",
	KeyNumpad7:              "NUMPAD_7",
	KeyNumpad8:              "NUMPAD_8",
	KeyNumpad9:              "NUMPAD_9",
	KeyNumpadAdd:            "NUMPAD_ADD",
	KeyNumpadBackspace:      "NUMPAD_BACKSPACE",
	KeyNumpadClear:          "NUMPAD_CLEAR",
	KeyNumpadClearEntry:     "NUMPAD_CLEAR_ENTRY",
	KeyNumpadComma:          "NUMPAD_COMMA",
	KeyNumpadDecimal:        "NUMPAD_DECIMAL",
	KeyNumpadDivide:         "NUMPAD_DIVIDE",
	KeyNumpadEnter:          "NUMPAD_ENTER",
	KeyNumpadEqual:          "NUMPAD_EQUAL",
	KeyNumpadMemoryAdd:      "NUMPAD_MEMORY_ADD",
	KeyNumpadMemoryClear:    "NUMPAD_MEMORY_CLEAR",
	KeyNumpadMemoryRecall:   "NUMPAD_MEMORY_RECALL",
	KeyNumpadMemoryStore:    "NUMPAD_MEMORY_STORE",
	KeyNumpadMemorySubtract: "NUMPAD_MEMORY_SUBTRACT",
	KeyNumpadMultiply:       "NUMPAD_MULTIPLY",
	KeyNumpadParenLeft:      "NUMPAD_PAREN_LEFT",
	KeyNumpadParenRight:     "NUMPAD_PAREN_RIGHT",
	KeyNumpadSubtract:       "NUMPAD_SUBTRACT",
	KeyNumpadSeparator:      "NUMPAD_SEPARATOR",
	KeyNumpadUp:             "NUMPAD_UP",
	KeyNumpadDown:           "NUMPAD_DOWN",
	KeyNumpadRight:          "NUMPAD_RIGHT",
	KeyNumpadLeft:           "NUMPAD_LEFT",
	KeyNumpadBegin:          "NUMPAD_BEGIN",
	KeyNumpadHome:           "NUMPAD_HOME",
	KeyNumpadEnd:            "NUMPAD_END",
	KeyNumpadInsert:         "NUMPAD_INSERT",
	KeyNumpadDelete:         "NUMPAD_DELETE",
	KeyNumpadPageUp:         "NUMPAD_PAGE_UP",
	KeyNumpadPageDown:       "NUMPAD_PAGE_DOWN",
	KeyEscape:               "ESCAPE",
	KeyF1:                   "F1",
	KeyF2:                   "F2",
	KeyF3:                   "F3",
	KeyF4:                   "F4",
	KeyF5:                   "F5",
	KeyF6:                   "F6",
	KeyF7:                   "F7",
	KeyF8:                   "F8",
	KeyF9:                   "F9",
	KeyF10:                  "F10",
	KeyF11:                  "F11",
	KeyF12:                  "F12",
	KeyF13:                  "F13",
	KeyF14:                  "F14",
	KeyF15:                  "F15",
	KeyF16:                  "F16",
	KeyF17:                  "F17",
	KeyF18:                  "F18",
	KeyF19:                  "F19",
	KeyF20:                  "F20",
	KeyF21:                  "F21",
	KeyF22:                  "F22",
	KeyF23:                  "F23",
	KeyF24:                  "F24",
	KeyF25:                  "F25",
	KeyFn:                   "FN",
	KeyFnLock:               "FN_LOCK",
	KeyPrintScreen:          "PRINT_SCREEN",
	KeyScrollLock:           "SCROLL_LOCK",
	KeyPause:                "PAUSE",
	KeyBrowserBack:          "BROWSER_BACK",
	KeyBrowserFavorites:     "BROWSER_FAVORITES",
	KeyBrowserForward:       "BROWSER_FORWARD",
	KeyBrowserHome:          "BROWSER_HOME",
	KeyBrowserRefresh:       "BROWSER_REFRESH",
	KeyBrowserSearch:        "BROWSER_SEARCH",
	KeyBrowserStop:          "BROWSER_STOP",
	KeyEject:                "EJECT",
	KeyLaunchApp1:           "LAUNCH_APP_1",
	KeyLaunchApp2:           "LAUNCH_APP_2",
	KeyLaunchMail:           "LAUNCH_MAIL",
	KeyMediaPlayPause:       "MEDIA_PLAY_PAUSE",
	KeyMediaSelect:          "MEDIA_SELECT",
	KeyMediaStop:            "MEDIA_STOP",
	KeyMediaTrackNext:       "MEDIA_TRACK_NEXT",
	KeyMediaTrackPrevious:   "MEDIA_TRACK_PREVIOUS",
	KeyPower:                "POWER",
	KeySleep:                "SLEEP",
	KeyAudioVolumeDown:      "AUDIO_VOLUME_DOWN",
	KeyAudioVolumeMute:      "AUDIO_VOLUME_MUTE",
	KeyAudioVolumeUp:        "AUDIO_VOLUME_UP",
	KeyWakeUp:               "WAKE_UP",
	KeyCopy:                 "COPY",
	KeyCut:                  "CUT",
	KeyPaste:                "PASTE",
}

// String returns the C enum member name, or "UNKNOWN(n)" for a value this
// build does not name.
func (k Key) String() string {
	if name, ok := keyNames[k]; ok {
		return name
	}
	return fmt.Sprintf("UNKNOWN(%d)", uint16(k))
}
