#!/usr/bin/env bash
# WBS 9.11 — build and package the macOS .app bundle.
#
#   packaging/macos-app.sh --probe    # report toolchain readiness, change nothing
#   packaging/macos-app.sh            # build, ad-hoc sign, verify, zip
#   packaging/macos-app.sh --no-sign  # build and zip without signing
#
# Where the bundle comes from
# ---------------------------
# The macOS app is NOT produced by `zig build` alone. `build.zig` wires up a
# `GhosttyXcodebuild` step that shells out to `xcodebuild -target Ghostty`.
# The chain is:
#
#   libghostty-internal fat archive  (zig, per-arch)
#     -> metallib Ghostty            (xcrun metal + xcrun metallib)   <-- needs
#     -> GhosttyKit.xcframework      (zig, lipo)                         the
#     -> macos/build/ReleaseLocal/Ghostty.app  (xcodebuild)          Metal
#     -> zig-out/Ghostty.app         (`cp -R`, because of symlinks)  toolchain
#
# The `.metallib` step is unconditional whenever the target is macOS, so the
# Metal toolchain component is a hard prerequisite for the app even though the
# default renderer is OpenGL. `src/build/MetallibStep.zig` only returns null for
# non-macOS targets.
#
# What is verifiable here
# -----------------------
# Whether the toolchain is present is fully verifiable, and the script records
# the exact failure when it is not. Whether the produced bundle *launches* is
# not verifiable in a headless container, and this script says so rather than
# claiming a smoke test it did not run.
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

MODE=build
SIGN=1
for arg in "$@"; do
  case "$arg" in
    --probe) MODE=probe ;;
    --no-sign) SIGN=0 ;;
    -h | --help) sed -n '2,34p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) die "unknown argument: $arg" ;;
  esac
done

VERSION="$(bash "$PKG_DIR/version.sh" --print)"
APP_NAME="Khostty"
BUNDLE="zig-out/Ghostty.app"
EVIDENCE="$OUT/macos/toolchain-probe.txt"
mkdir -p "$OUT/macos" "$LOG_DIR"

# ---------------------------------------------------------------- 1. probe --

step "probing the macOS toolchain"

probe_status="ok"
probe_notes=()

record() { probe_notes+=("$1"); log "    $1"; }

if ! have xcodebuild; then
  probe_status="blocked"
  record "xcodebuild: MISSING (install Xcode)"
else
  xcode_ver="$(xcodebuild -version 2>/dev/null | tr '\n' ' ' | sed 's/ *$//')"
  record "xcodebuild: $xcode_ver"
fi

if ! have xcrun; then
  probe_status="blocked"
  record "xcrun: MISSING"
else
  record "developer dir: $(xcode-select -p 2>/dev/null || echo UNKNOWN)"
fi

# `xcrun --find metal` can resolve to a path whose toolchain component is not
# installed: on Xcode 16+ the Metal compiler ships as a downloadable component.
# So the path lookup is not sufficient evidence. Compile a one-line no-op shader
# and see whether the driver actually runs.
metal_probe_dir="$(mktemp -d)"
cat >"$metal_probe_dir/probe.metal" <<'METAL'
#include <metal_stdlib>
using namespace metal;
kernel void khostty_probe(device float *out [[buffer(0)]], uint i [[thread_position_in_grid]]) { out[i] = 0.0; }
METAL
set +e
xcrun -sdk macosx metal -c "$metal_probe_dir/probe.metal" -o "$metal_probe_dir/probe.ir" \
  >"$metal_probe_dir/out.txt" 2>&1
probe_rc=$?
set -e
if [[ "$probe_rc" -ne 0 ]]; then
  probe_status="blocked"
  record "metal compiler: NOT USABLE (exit $probe_rc)"
  record "  $(head -1 "$metal_probe_dir/out.txt")"
else
  record "metal compiler: usable"
fi
rm -rf "$metal_probe_dir"

# Deliberately records only the *kind* and *count* of identities, never the
# identity string: the subject name and team ID are personal data and this file
# is committed to the repository.
SIGN_IDENTITY=""
if have security; then
  id_count="$(security find-identity -v -p codesigning 2>/dev/null | awk '/valid identities found/{print $1}')"
  if security find-identity -v -p codesigning 2>/dev/null | grep -q "Developer ID Application"; then
    SIGN_IDENTITY="Developer ID Application"
    record "codesigning identity: 1+ Developer ID Application present (of ${id_count:-?} valid)"
  else
    record "codesigning identity: no Developer ID Application (${id_count:-0} other valid identities)"
  fi
else
  record "codesigning identity: UNKNOWN (no security tool)"
fi

# Notarization needs stored notarytool credentials or App Store Connect keys.
# Those are secrets and are not present, so notarization is out of scope here.
set +e
xcrun notarytool history >/dev/null 2>&1
notary_rc=$?
set -e
if [[ "$notary_rc" -eq 0 ]]; then
  record "notarytool credentials: present"
else
  record "notarytool credentials: NOT configured (notarization impossible on this host)"
fi

{
  echo "# macOS toolchain probe"
  echo "# generated by packaging/macos-app.sh --probe"
  echo "# date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "status: $probe_status"
  for n in "${probe_notes[@]}"; do printf 'detail: %s\n' "${n#  }"; done
} >"$EVIDENCE"
log "    evidence written to $EVIDENCE"

if [[ "$probe_status" != "ok" ]]; then
  warn "the macOS .app bundle CANNOT be built on this host"
  warn "  reason: the Metal toolchain component is not installed"
  warn "  remediation, on a machine where it can be downloaded:"
  warn "    xcodebuild -downloadComponent MetalToolchain"
  warn "  this host: that command fails with"
  warn "    Failed fetching catalog for assetType (com.apple.MobileAsset.MetalToolchain)"
  warn "  so the bundle is UNVERIFIED on macOS and is not part of the release manifest"
fi

if [[ "$MODE" == "probe" ]]; then
  printf '%s\n' "$probe_status"
  exit 0
fi

[[ "$probe_status" == "ok" ]] \
  || die "refusing to continue: the app build would fail at the metallib step (see $EVIDENCE)"

# ----------------------------------------------------------------- 2. build --

step "building the macOS app bundle (zig build -Demit-macos-app, ReleaseSafe)"
# ReleaseSafe maps to the Xcode `ReleaseLocal` configuration, which is what
# dist/macos and the xctest plan expect for a non-notarized local release.
if ! zig_build -Demit-macos-app -Doptimize=ReleaseSafe >"$LOG_DIR/macos-app-build.log" 2>&1; then
  tail -30 "$LOG_DIR/macos-app-build.log" >&2
  die "zig build failed; full log at $LOG_DIR/macos-app-build.log"
fi

[[ -d "$BUNDLE" ]] || die "build reported success but $BUNDLE does not exist"
APP_BIN="$BUNDLE/Contents/MacOS/ghostty"
[[ -f "$APP_BIN" ]] || die "$BUNDLE has no Contents/MacOS/ghostty"

built_version="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$BUNDLE/Contents/Info.plist" 2>/dev/null || echo UNKNOWN)"
built_bundle_id="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$BUNDLE/Contents/Info.plist" 2>/dev/null || echo UNKNOWN)"
ok "built $BUNDLE (CFBundleShortVersionString=$built_version, id=$built_bundle_id)"

# ------------------------------------------------------------- 3. signature --

if (( SIGN )); then
  if [[ -n "$SIGN_IDENTITY" ]]; then
    step "signing with \"$SIGN_IDENTITY\" (identity located by name prefix)"
    SIGN_ARG=(-s "$SIGN_IDENTITY" --options runtime)
    SIGN_KIND="developer-id"
  else
    step "ad-hoc signing (no Developer ID identity on this host)"
    # Ad-hoc means no certificate, so Gatekeeper will quarantine the bundle on
    # another machine. Stated in the evidence file rather than papered over.
    SIGN_ARG=(-s -)
    SIGN_KIND="adhoc"
  fi
  codesign --force --deep "${SIGN_ARG[@]}" --timestamp=none "$BUNDLE" \
    >"$LOG_DIR/macos-codesign.log" 2>&1 \
    || die "codesign failed; see $LOG_DIR/macos-codesign.log"
  codesign --verify --deep --strict --verbose=2 "$BUNDLE" \
    >>"$LOG_DIR/macos-codesign.log" 2>&1 \
    || die "codesign --verify failed; see $LOG_DIR/macos-codesign.log"
  codesign -dv "$BUNDLE" >"$OUT/macos/codesign-report.txt" 2>&1 || true
  ok "ad-hoc signature verifies (${BUNDLE})"
  warn "signature is ad-hoc: Gatekeeper will quarantine this on other machines"
else
  unverified "signing skipped (--no-sign)"
fi

# ------------------------------------------------------------ 4. package up --

step "zipping the bundle"
ZIP="$OUT/macos/$APP_NAME-$VERSION-macos.zip"
rm -f "$ZIP"
# `ditto` is required rather than `zip`: the bundle contains symlinks, and a
# plain zip would dereference or drop them.
ditto -c -k --sequesterRsrc --keepParent "$BUNDLE" "$ZIP"
ZIP_SHA="$(sha256 "$ZIP")"

# ------------------------------------------------------------- 5. evidence --

step "recording evidence"
{
  echo "# macOS .app bundle — build evidence"
  echo "# generated by packaging/macos-app.sh"
  echo "# date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "khostty_version: $VERSION"
  echo "source_commit: $(git -C "$REPO_ROOT" rev-parse HEAD)"
  echo "bundle_path: $BUNDLE"
  echo "bundle_version: $built_version"
  echo "bundle_id: $built_bundle_id"
  echo "xcode: $(xcodebuild -version 2>/dev/null | tr '\n' ' ')"
  echo "signed: $([[ $SIGN == 1 ]] && echo "${SIGN_KIND:-unknown}" || echo no)"
  echo "notarized: no"
  echo "signing_identity_kind: ${SIGN_KIND:-none} (name withheld: personal data)"
  echo "notarization_blocker: no Developer ID Application identity and no notarytool credentials in this container"
  echo "launch_verified: NO — the bundle was not executed"
  echo "launch_unverified_reason: SIGKILL-on-launch is expected for an un-notarized bundle started outside a logged-in GUI session; this container has no GUI session, so a launch test would prove nothing either way."
  echo "zip: $(basename "$ZIP")"
  echo "zip_sha256: $ZIP_SHA"
  echo "zip_bytes: $(wc -c <"$ZIP" | tr -d ' ')"
} >"$OUT/macos/EVIDENCE.txt"

( cd "$OUT/macos" && sums_line "$ZIP" >"$(basename "$ZIP").sha256" )

step "done"
cat >&2 <<SUMMARY
  artifact      $ZIP
  size          $(human_size "$ZIP")
  sha256        $ZIP_SHA
  bundle        $BUNDLE (version $built_version)
  signature     $([[ $SIGN == 1 ]] && echo "ad-hoc (verifies)" || echo "none")
  notarized     no — no Developer ID / notarytool credentials available
  launch test   not run — see $OUT/macos/EVIDENCE.txt
  logs          $LOG_DIR/
SUMMARY
