// Command genkeys regenerates keys_gen.go from the linked library's own type
// manifest.
//
// The GhosttyKey enum has 177 members. Transcribing them by hand would be both
// tedious and easy to get subtly wrong, so they are derived from
// ghostty_type_json() instead. Run from khostty-go:
//
//	go run ./tools/genkeys > keys_gen.go
//
// The output is checked in, and TestGeneratedKeysMatchManifest re-derives every
// value from the manifest so a stale table fails the suite rather than
// selecting the wrong key.
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	khostty "github.com/KooshaPari/Khostty/khostty-go"
)

// goName converts a manifest member name into an exported Go identifier.
//
// The manifest strips the C prefix, so members arrive as SCREAMING_SNAKE_CASE
// with digits already attached to their word (DIGIT_0, F12, NUMPAD_ADD).
func goName(member string) string {
	parts := strings.Split(strings.ToLower(member), "_")
	var b strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}
	return b.String()
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "genkeys: "+format+"\n", args...)
	os.Exit(1)
}

func main() {
	m, err := khostty.ParseManifest(khostty.TypeManifest())
	if err != nil {
		fail("parsing manifest: %v", err)
	}

	values, ok := m.EnumValues("GhosttyKey")
	if !ok {
		fail("manifest has no GhosttyKey enum")
	}

	type member struct {
		Go   string
		Val  int
		Orig string
	}
	members := make([]member, 0, len(values))
	for name, val := range values {
		// The sentinel is an enum-width guard, not a key.
		if strings.HasSuffix(name, "MAX_VALUE") {
			continue
		}
		members = append(members, member{Go: "Key" + goName(name), Val: val, Orig: name})
	}
	sort.Slice(members, func(i, j int) bool {
		if members[i].Val != members[j].Val {
			return members[i].Val < members[j].Val
		}
		return members[i].Go < members[j].Go
	})

	var b strings.Builder
	b.WriteString("// Code generated by tools/genkeys from libghostty-vt's own type\n")
	b.WriteString("// manifest. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Regenerate with:\n")
	b.WriteString("//\n")
	b.WriteString("//\tgo run ./tools/genkeys > keys_gen.go\n\n")
	b.WriteString("package khostty\n\n")
	b.WriteString("import \"fmt\"\n\n")
	b.WriteString("// Physical key codes, mirroring GhosttyKey. The C enum is backed by\n")
	b.WriteString("// int, so Key is int32 for a direct cast.\n")
	b.WriteString("//\n")
	b.WriteString("// The values come from the linked library, so they always match the build\n")
	b.WriteString("// these bindings are used with.\n")
	b.WriteString("const (\n")
	for _, mem := range members {
		fmt.Fprintf(&b, "\t%s Key = %d\n", mem.Go, mem.Val)
	}
	b.WriteString(")\n\n")
	b.WriteString("// keyNames maps every generated key constant back to its C name, for\n")
	b.WriteString("// error messages and test failures.\n")
	b.WriteString("var keyNames = map[Key]string{\n")
	for _, mem := range members {
		fmt.Fprintf(&b, "\t%s: %q,\n", mem.Go, mem.Orig)
	}
	b.WriteString("}\n\n")
	b.WriteString("// String returns the C enum member name, or \"UNKNOWN(n)\" for a value this\n")
	b.WriteString("// build does not name.\n")
	b.WriteString("func (k Key) String() string {\n")
	b.WriteString("\tif name, ok := keyNames[k]; ok {\n\t\treturn name\n\t}\n")
	b.WriteString("\treturn fmt.Sprintf(\"UNKNOWN(%d)\", int32(k))\n}\n")

	if _, err := os.Stdout.WriteString(b.String()); err != nil {
		fail("writing output: %v", err)
	}
}
